# Generated by Django 4.2 on 2023-04-28 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Бренд')),
                ('img', models.ImageField(upload_to='media/Brand_img')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Name product')),
                ('description', models.TextField(verbose_name='description')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_app.brand', verbose_name='Product name')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default='35', verbose_name='size')),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.products', verbose_name='Product name')),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.IntegerField(default='5', verbose_name='quant')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.products', verbose_name='Product name')),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.size', verbose_name='Size')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default='0.00', verbose_name='price')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.products', verbose_name='Product name')),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.size', verbose_name='Size')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/Product_img', verbose_name='image')),
                ('product_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.products', verbose_name='Product name')),
            ],
        ),
    ]
