# Generated by Django 4.2 on 2023-04-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_alter_brand_options_alter_images_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='img',
            field=models.ImageField(upload_to='Brand_img'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='Product_img', verbose_name='image'),
        ),
    ]
