# Generated by Django 4.2 on 2023-04-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_alter_products_brand_alter_products_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='product_size',
        ),
        migrations.AddField(
            model_name='size',
            name='price',
            field=models.FloatField(default='0.00', verbose_name='price'),
        ),
        migrations.AddField(
            model_name='size',
            name='quant',
            field=models.IntegerField(default='5', verbose_name='quant'),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
