# Generated by Django 4.2 on 2023-04-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_remove_quantity_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image1',
            field=models.ImageField(blank=True, upload_to='Product_img', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='images',
            name='image2',
            field=models.ImageField(blank=True, upload_to='Product_img', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='images',
            name='image3',
            field=models.ImageField(blank=True, upload_to='Product_img', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='images',
            name='image4',
            field=models.ImageField(blank=True, upload_to='Product_img', verbose_name='image'),
        ),
    ]
