# Generated by Django 4.2 on 2023-05-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_images_image1_images_image2_images_image3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='product_size',
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, upload_to='Product_img', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.FloatField(default='0.00', null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='products',
            name='quant',
            field=models.IntegerField(default='5', null=True, verbose_name='quant'),
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.IntegerField(default='35', null=True, verbose_name='size'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
