# Generated by Django 4.2 on 2023-05-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0008_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='gender',
            field=models.CharField(max_length=100, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='products',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('for kids', 'for kids')], max_length=100, null=True, verbose_name='Gender'),
        ),
    ]
