# Generated by Django 4.2 on 2023-05-04 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_app', '0012_alter_brand_options_alter_cart_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default='35', null=True, verbose_name='size')),
                ('price', models.FloatField(default='0.00', null=True, verbose_name='price')),
                ('quant', models.IntegerField(default='5', null=True, verbose_name='quant')),
                ('title', models.CharField(max_length=50, verbose_name='Name product')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(null=True, upload_to='Product_img', verbose_name='image')),
                ('gender', models.CharField(max_length=100, null=True, verbose_name='Gender')),
                ('create_data', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_data', models.DateTimeField(auto_now=True, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_app.brand', verbose_name='Brand')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_app.products', verbose_name='Brand')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Favorite',
                'ordering': ['-create_data', '-update_data'],
            },
        ),
    ]
